### ISSUE TITLE
Dealing with several clients

### ISSUE THREAD

**Issue by sstativa** [ZombieAlex/MFCAuto#10]
What is a right way to deal with several clients in the code?

I have n+1 clients:
* one global and "permanent" to manage the list of models (created on start)
* and one per each model (created dynamically and usually not more than 5)

I've noticed that if a model goes offline and I call `disconnect` to her client instance, the list of known models will be "reset" and it will take a while to propagate the list of models again.

**Comment by ZombieAlex** [comment]
There's logic within the Client class to keep a global count of currently connected clients and only reset the model list when there are none.

Sounds like I have a bug in that logic from what you're describing. I'll track it down when I get time. Feel free to issue a PR if you find it first.

Thanks for the report.

**Comment by ZombieAlex** [comment]
Quick follow-up here. The [reset code is here](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/Client.ts#L856).  Somehow `Client.connectedClientCount` is reaching 0 in your scenario when it sounds like it shouldn't be.

As a cheap workaround for now you could manually set that value to some arbitrary number >0 and Client wouldn't reset things.  The value only controls the reset mechanism, it wouldn't impact anything else.

Also, not sure exactly what scenario you have, but a single Client can handle many scenarios. One Client can join as many model's rooms as desired, for instance. Then if you're listening to Client events like `client.on("CMESG", (packet) => { /* Do Stuff */ })` you can distinguish which model room the packet was about using the [`packet.aboutModel`](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/Packet.ts#L38) property which will return the instance of the Model receiving the chat in this case.  I tried to make `aboutModel` apply to as many different packet types as possible, not just `FCTYPE.CMESG` packets.

All that said, multiple Clients is a supported scenario. I'll get this fixed.

**Comment by sstativa** [comment]
Honestly, I have not tried to use one client to join several rooms, however I doubt it will work in my scenario. I'm dealing with rtmpdump and to be able to dump the stream I have to join the model's room first, otherwise there will be AuthError. 

I'll probably try to make a test later to see what happens in case of one client.

**Comment by sstativa** [comment]
I've just had some time to inspect your code. I have an idea where the problem is but I need your opinion on it. 

You increment `connectedClientCount` only if `doLogin` is `true` ([link](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/Client.ts#L776)), however in my case I create a client without auto login, because I have to exchange some messages with server before logging in. Also, you `login` method do not increase the `connectedClientCount`.

My guess will be that the line [781](https://github.com/ZombieAlex/MFCAuto/blob/master/src/main/Client.ts#L781) should be in `login` method.

**Comment by sstativa** [comment]
Btw,
When I opened this issue I temporary commented out the line in my code where I was calling `disconnect` method, so today my script failed (after working for several days) because nodejs could not allocate more memory.

So, the question, if in my code there is no more references to the client, will this client "die" somehow and be freed by the garbage collector?

Simplified example, 
```
var a = [];

function add() {
  var c = new mfc.client();

  c.connect(false).then(() => {
    // some code 
  });

  a.push(c);
}

add();

// some code

a.splice(0, 1);
```

**Comment by ZombieAlex** [comment]
To your question, no it won't die if left connected. After connecting, Clients will be referenced and kept alive by the NodeJS event loop handling the socket connection and the `keepAlive` ping.

As for the bug, I think your fix is correct.  I don't have any such late-login scenarios on my end so that issue didn't occur to me.

Feel free to issue a PR, or I'll fix it myself sometime later today.  Thanks.
