### ISSUE TITLE
Incomplete records

### ISSUE THREAD

**Issue by sstativa** [ZombieAlex/MFCAuto#11]
Suppose MFC changes something recently because I started to experience this issue only recently.

To get an array of models I used this block
```
mfc.Model.knownModels.forEach(m => {
  if (m.bestSession.vs !== mfc.STATE.Offline && m.bestSession.camserv > 0) {
    models.push({
      // ... some fields from bestSession
    });
  }
}
```
and `bestSession` used to have almost all main properties (such as `uid`, `vs`, `nm`, etc), however, now I get some `bestSession` without `nm` property which is very important to me. This is an example: 
```
{
  sid: 305186818,
  uid: 16322838,
  vs: 2,
  pid: 1,
  hidecs: true,
  rc: 7,
  camscore: 390.7,
  camserv: 211
}
```

Do you have any ideas why `nm` is absent? I suppose I might do it wrong or MFC really changed something. Is there any other solution where I can get the list of online models?

**Comment by sstativa** [comment]
MFC is down for now to do any tests. I'll let you know if the problem persist when the service returns back to normal.

**Comment by ZombieAlex** [comment]
MFC was down or only partially working for about 5 hours yesterday. Depending on when you saw this, I'd suspect that the servers were just acting up.

That said, I have seen model records occasionally come from the server without names before, very infrequently though. And I can say that all of my scripts are running fine right now and displaying proper model names.

If it becomes more common, I'm happy to investigate.

**Comment by sstativa** [comment]
Closed for now, because I have no more errors in the log. Suppose you were right, it was the servers issue.
