### ISSUE TITLE
extension of API?

### ISSUE THREAD

**Issue by infoberg03** [ZombieAlex/MFCAuto#14]
Hi,
would it be possible to add a function for joining a group chat? I read that there is an event to attach to so one can react to status changes, but what would one need to do to join the group, if being logged in with a real user?

**Comment by ZombieAlex** [comment]
Should be possible, yes. Something like this might already work:

```javascript
const mfc = require("MFCAuto");

let client = new mfc.Client(yourUserName, yourHashedPassword);

// Get any model, AspenRae in this case
let AspenRae = mfc.Model.getModel(3111899);
AspenRae.on("vs", (model, before, after) => {
    // Wait for AspenRae to enter a group show
    if (after === mfc.STATE.GroupShow) {
        // Join her room
        // (I'm not certain if joining the room is
        // required before joining a group, but it's
        // the typical website flow)
        client.joinRoom(model.uid)
            .then(() => {
                // Join the group (?)
                client.TxCmd(mfc.FCTYPE.REQUESTGRP, 0, model.bestSessionId, 0);
            })
            .catch(() => {
                // joinRoom might reject if you're banned
            });
    }
});

client.connect();
```

I haven't tested that though. If it does work, it will still require your account to have tokens and it will spend them. Be aware of that if you try it.

**Comment by infoberg03** [comment]
Great starter, thanks. I am working on enhancing Horacios version of MFC-Node, but it will take me some learning as I have never touching Node.js development before...

**Comment by infoberg03** [comment]
But to be honest, I doubt if group can be recorded. MFC-Node just spawns a ffmpeg process after getting the video URL. But I guess in a group show, the request for the URL will somehow be validated to make sure the video is being sent to a client who joined the group. Maybe I just need to start a new capture process after joining the show...

**Comment by infoberg03** [comment]
To be honest, I am running into several issues where I don't know how to best solve them.

1) I am trying to also log chat messages. This works only if not more than 1 model is being recorded, I am using the code you gave as a sample:

var mfc = require("MFCAuto");
var client = new mfc.Client();
var modelId = 3111899; //AspenRae's model id which can be discovered by running the previous example among other means

//Wait for video state updates for a specific model
mfc.Model.getModel(modelId).on("vs", function(model,oldState,newState){
    if(newState !== mfc.FCVIDEO.OFFLINE) //When she's online
        client.joinRoom(modelId); //Join her room
});

//Listen for chat messages and print them
client.on("CMESG", function(packet){
    if(packet.chatString !== undefined){
        console.log(packet.chatString);
    }
});

//Listen for tip messages and print them
client.on("TOKENINC", function(packet){
    if(packet.chatString !== undefined){
        console.log(packet.chatString);
    }
});

//Connect to MFC and begin processing events
client.connect();

Is there a way to receive the messages not at the client level but for the individual model?

2) in my inital tests last night the connection would always drop in a group show, i.e. recording would start and immediatley stop, but I guess that's an issue in Horacios MFC-Node code, I will try to ask there :) Also his code is not making development too easy for me as he does not keep the model objects in a collection, but rather just a collection of the properties as strings. Plus I need to understand promises :D

**Comment by ZombieAlex** [comment]
For your first issue, the client callbacks for CMESG and TOKENINC will be invoked for messages sent to any chat rooms you're currently in, and you can distinguish which model's room the packet is for by checking `packet.aboutModel` on the given packet.

I haven't looked at Horacio's code or had a chance to look further into the handshake that happens when you join a group. The code I posted before was pulled from inspecting the MFC source for the specific event handlers invoked when you click the "join group" link. It's possible there's an additional challenge check after that.

I believe that what you want to accomplish is possible, but you'll need to work through exactly what messages are sent to and from the server when joining a group.  One way to do that is to load MFC with "?debug" at the end of the URL and then open the browser debug console, F12. In debug mode, MFC will print all the messages being sent back and forth for your live session. So you can join a group in the browser and see what is supposed to happen, then translate that to MFCAuto.

**Comment by infoberg03** [comment]
Great, thanks for the insight regarding the debug mode for MFC. Maybe I will just have to kill the current recording process, join the room and the group and then start another recording process. I will keep you updated if and when I make progress, will be away for a few days.

I am already working on the first issue, got the idea of how these messages work by looking at the Packet.js code :)

**Comment by infoberg03** [comment]
Hmmm, I guess I am doing something wrong. From MFC debug mode I gathered these 2 commands which are triggered when joining a group show.

TX: FCTYPE_JOINCHAN      51 668302391 0 125794870 2
TX: FCTYPE_JOINCHAN      51 668302391 0 225794870 9

51 is the number of FCTYPE.JOINCHAN, but I am not sure  about those other parameters, 0 and 2 in line 1 and 0 and 9 in line 2
Your API has the following definition of the TxCommand:
TxCmd(nType: FCTYPE, nTo: number = 0, nArg1: number = 0, nArg2: number = 0, sMsg: string = null)
So I was trying to send
client.TxCmd(mfc.FCTYPE.JOINCHAN, mfcClient.sessionId, 0, myModel.bestSessionId, 2)
client.TxCmd(mfc.FCTYPE.JOINCHAN, mfcClient.sessionId, 0, myModel.bestSessionId, 9)

But it threw an error 👍 

C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:285
                throw new Error(`Error handling websocket packet: \n\t${e}\n\t"${originalMessage}"`);
                ^

Error: Error handling websocket packet:
        ReferenceError: client is not defined

I think I am totally lost as to what these IDs mean...

**Comment by infoberg03** [comment]
did another test.

joining the room of MargoTess:
 TX: FCTYPE_JOINCHAN      51 669287923 0 123880134 9

joining her group:
 TX: FCTYPE_JOINCHAN      51 669287923 0 123880134 2
 TX: FCTYPE_JOINCHAN      51 669287923 0 223880134 9

**Comment by ZombieAlex** [comment]
Alright, getting closer then. I can help explain the messages a little bit.

> TX: FCTYPE_JOINCHAN 51 668302391 0 125794870 2

This command is leaving the model's public chat. It's the same command sent whenever you leave the public room for any reason. It's not specific to joining the group and I believe it could be ommitted.

- 51 is the nType `FCTYPE.JOINCHAN`, like you said. The debug output just prints both forms for readability. This doesn't, by itself, mean you're joining the room. It's just indicating that this message is generally about joining/leaving rooms or "channels".
- 668302391 is your session ID. Don't specify that in your `TxCmd` call. **All** commands from the client have to specify your own session ID. It's a required parameter. So MFCAuto fills that in for you.
- 0 is nTo, and its meaning varies depending on the `FCTYPE` of the message. 0 probably means it isn't important for this command.
- 125794870 is nArg1. For `JOINCHAN` commands this is the room ID, not session ID, of the model you referencing. You can get the room ID via `client.toRoomId(model.uid)`. Room IDs are just model IDs plus 100000000
- 2 is nArg2, and for `JOINCHAN` packets it's usually an `FCCHAN` value (see Constants.ts). 2 is `FCCHAN.PART`, meaning to leave the room. You can view the `Client.leaveRoom` code for an example of this.

> TX: FCTYPE_JOINCHAN 51 668302391 0 225794870 9

This is far more interesting. In this case nArg1 looks like the model's ID plus 200000000. Perhaps that's how group room IDs are formed.

And 9, if it's an FCCHAN argument, maps to `FCCHAN.EVENT_RESERVED_004`, which is bizarre. Perhaps that means `FCGROUP.SESSION` instead. Might make more sense.

In any case, if that's all there is to joining a group, then this should work:

`client.TxCmd(mfc.FCTYPE.JOINCHAN, 0, myModel.uid + 200000000, 9)`

**Comment by ZombieAlex** [comment]
And if that works, then I expect `packet.aboutModel` might fail and return undefined for chat from the group show, because I didn't realize channels could go up to 200000000.

If I'm right and it fails, you could get the target model ID for the incoming CMESG or TOKENINC packet via `packet.nTo - 200000000` instead of relying on `.aboutModel`

**Comment by ZombieAlex** [comment]
Just released v4.2.0 which has a fix to the `packet.aboutModel` issue mentioned in my last comment. I've done no further research around what it takes to join groups though.

**Comment by infoberg03** [comment]
Hi,

I updated to the new version, going to experiment with what you posted. But it's a little bit difficult to time all the testing and starting of group shows "manually" :)

So far I ran into a problem when trying to log the chat. I am hooking into CMESG and TOKENINC like so:

	//create events for chat messages
	//Listen for chat messages and print them
	mfcClient.on("CMESG", function(packet){
		if(packet.chatString !== undefined){
			logChat(packet);
		}
	});
	//Listen for tip messages and print them
	mfcClient.on("TOKENINC", function(packet){
		if(packet.chatString !== undefined){
			logChat(packet);
		}
	});


But then what happens after a short while is the following exception:

C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:315
                throw new Error(`Error handling websocket packet: \n\t${e}\n\t"${originalMessage}"`);
                ^

Error: Error handling websocket packet:
        TypeError: path must be a string or Buffer
        "20 691316570 691128305 0 19571286 {%22pid%22:1,%22sid%22:691316570,%22uid%22:19571286,%22m%22:{%22hidecs%22:true,%22rc%22:6,%22topic%22:%22101%2520happy%2520to%2520see%2520me%252C80%2520for%2520smile%252C99%2520spank%2520me%252C115%2520like%2520me%252C333%2520dance%252C1115%2520one%2520glass%2520%2520redwine%22}}"
    at Client._readWebSocketPacket (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:315:23)
    at Client._readWebSocketData (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:47:14)
    at WebSocket.client.on (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:659:34)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (C:\mfc-node2\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (C:\mfc-node2\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\mfc-node2\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\mfc-node2\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\mfc-node2\node_modules\ws\lib\Receiver.js:139:10)
    at Socket._ultron.on (C:\mfc-node2\node_modules\ws\lib\WebSocket.js:139:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)

Is that coming from one of those 2 messages?

**Comment by ZombieAlex** [comment]
That error happens consistently? Seems like a bug in the Client when dealing with WebSockets connections unrelated to group shows. I'll look into it but for now a simple workaround would be to disable WebSockets. `useWebSockets: false` in the options bag, or just don't specify `useWebSockets: true`, the default is to not use it.

Without WebSockets, the code that's throwing there won't be executed.

**Comment by ZombieAlex** [comment]
On further thought, that might actually be coming from your code in one of your callback handlers. Any error thrown in a Client or Model event callback would bubble up and be caught by MFCAuto there and cause an exception like that.

I don't see anything clearly wrong with the packet it printed, so I suspect your callbacks. But again, I wouldn't completely rule out issues with the WebSocket code since it's fairly new.

**Comment by infoberg03** [comment]
Thanks, I will try to disable websockets to see if its from my code. The function I call does nothing fancy, except for checking if it is a tip or chat message. Maybe I will just use 2 different functions, that will be the easiest route. It might actually be that the error always occurs on tip messages :)

**Comment by infoberg03** [comment]
So the error I get is not due to websockets being used or not. It happens every time a tip is being logged, but if a bot is running it happens after the bots CMESG is received. Take a look at this sample:

[01:23:33] [DEBUG] entering logChat with msg: {"FCType":"TOKENINC","nFrom":0,"nTo":109730911,"nArg1":10,"nArg2":0,"sMessage":{"ch":109730911,"flags":24832,"m":[694818243,9730911,"Sunhiee"],"sesstype":10,"stamp":1509582214,"tokens":16,"u":[694955095,19907151,"lamento"]},"_chatString":"lamento has tipped Sunhiee 16 tokens."}
[01:23:35] [DEBUG] entering logChat with msg: {"FCType":"CMESG","nFrom":656840028,"nTo":109730911,"nArg1":0,"nArg2":0,"sMessage":{"lv":2,"msg":"16 is not a winning number.","nm":"CharlesBot","pid":1,"sid":656840028,"uid":19863002,"vs":90,"u":{"chat_color":"FF0000"}},"_pMessage":"16 is not a winning number.","_chatString":"CharlesBot: 16 is not a winning number."}
C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:315
                throw new Error(`Error handling websocket packet: \n\t${e}\n\t"${originalMessage}"`);
                ^

Error: Error handling websocket packet:
        TypeError: path must be a string or Buffer
        "20 694818243 695354048 0 9730911 {%22pid%22:1,%22sid%22:694818243,%22uid%22:9730911,%22m%22:{%22hidecs%22:true,%22rc%22:174,%22topic%22:%22Smile111%257CLove1111%257CPantsoff4634%252Bshot%257C%25235-%2520Shot-1999%252FC2C-999%257CSpank-567%257C444-PM%257C200-Song%257CWheel333%252Fbigwheel1999%257CHi-Lo299%257CSoloVid3999-GG6999%257C%22}}"
    at Client._readWebSocketPacket (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:315:23)
    at Client._readWebSocketData (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:47:14)
    at WebSocket.client.on (C:\mfc-node2\node_modules\MFCAuto\lib\Client.js:659:34)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage (C:\mfc-node2\node_modules\ws\lib\WebSocket.js:143:47)
    at Receiver.dataMessage (C:\mfc-node2\node_modules\ws\lib\Receiver.js:389:14)
    at Receiver.getData (C:\mfc-node2\node_modules\ws\lib\Receiver.js:330:12)
    at Receiver.startLoop (C:\mfc-node2\node_modules\ws\lib\Receiver.js:165:16)
    at Receiver.add (C:\mfc-node2\node_modules\ws\lib\Receiver.js:139:10)
    at Socket._ultron.on (C:\mfc-node2\node_modules\ws\lib\WebSocket.js:139:22)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at Socket.Readable.push (_stream_readable.js:211:10)

Both messages were logged to my logfile, only after that the error occurred.

**Comment by ZombieAlex** [comment]
What is the error and callstack with WebSockets off?

**Comment by ZombieAlex** [comment]
Asking because the way I'm dealing with exceptions on the WebSocket code path is wrong. You'd get the exact same callstack for literally any exception for any uncaught issue in any event handler or any bug in MFCAuto. So this callstack isn't useful for understanding the issue.

Fortunately the non-websocket path is a little more sane with exceptions and might actually point to the code having the problem.

I've opened issue #16 to track the error reporting issue when using WebSockets.

**Comment by ZombieAlex** [comment]
If you'd like to continue using WebSockets for whatever reason, I just pushed a fix to #16. If you pull the latest from master and run your scenario again we should get the correct callstack.

**Comment by infoberg03** [comment]
I am nearly done with all the chat logging etc, going to test the group feature over th weekend. Thanks for your support, you library is an amazing piece of work!

**Comment by infoberg03** [comment]
Well, I think most pieces of the puzzle are technically clear and your library supports all the necessary transactions. But I am running into some issues implementing it into mfc-node, I will try to see if sstativa can give me a hand, maybe he could need a few more coffees :)

**Comment by infoberg03** [comment]
So I had some time to get back to this and I am running into what I believe are timing issues. If I use the TxCmd you specified before, the recording starts and immediately stops. I suspect that it is started before the grp room is successfully joined. And since TxCmd isn't an even emitter, I cannot use .then() 
Is there a way to achieve the same using joinRoom?

**Comment by ZombieAlex** [comment]
I can't speak to the recording part. That's beyond the scope of my code. But does the TxCmd successfully join the group? Are you receiving CMESG's from the group? If yes, then you could just do the TxCmd and then wait for the first CMESG from the channel to confirm you're in the group.

That's essentially what .joinRoom is doing. And there's usually some initial CMESG from the server itself saying something like "You have joined SoAndSo's room", so it's not like you are waiting for someone to actually speak in the group.

**Comment by infoberg03** [comment]
The actual joining seems to be working as I logged messages from group, for example:

[2017-11-26 23-06-41] FCServer: You have joined XXX's public chat.
[2017-11-26 23-06-41] FCServer: topic here 
...
[2017-11-26 23-06-41] FCServer: You have joined XXX's group show.
[2017-11-26 23-06-41] FCServer: topic here
[2017-11-26 23-06-41] FCServer: Group shows cost only 10 tokens per minute so members are highly encouraged to Tip the model, especially for personal requests. :)
[2017-11-26 23-06-41] ....
[2017-11-26 23-06-41] ....
[2017-11-26 23-06-42] recording end: Model XXX, id YYY, rank 0, camscore 000, desc: ZZZ

but nothing gets recorded, so maybe there is more to it than we think. Or it is just the timing, but I tried not to mess up the code by sstativa, just making small insertions where necessary. I will ask him if he has any ideas...

**Comment by ZombieAlex** [comment]
Have you figured this out yet? Once again, recording is beyond the scope of my code. However, my best guess is that perhaps you didn't change the piece of code on your end that's constructing the URL of the model's video stream.

As we've seen, to join a group chat you need to join the room using the model's ID plus 200000000. If you didn't change the URL construction code, it's probably using the model's ID plus 100000000, which would be her public chat video stream.

That part very likely needs to be changed to 200000000 as well.
