### ISSUE TITLE
Publish on NPM?

### ISSUE THREAD

**Issue by ZombieAlex** [ZombieAlex/MFCAuto#20]
For some time now I've debated publishing the package. Doing so has some pros and cons:

- Pros
  - Easier to find and install the package, no git requirement etc
  - Easier for consumers to adhere to symver and avoid breaking changes as I update master
- Cons
  - Would need to rename the package. Some time after I created this as "MFCAuto" they started to enforce that all package names must be lower case. I've avoided doing that because it's a breaking change to all consumers at this point.
  - Would be an additional burden on me dealing with the overhead of publishing and managing versions
  - Increased visibility for this package *could* be a bad thing. I could envision an arms race with the site trying to lock out node clients if usage became too much

If you're a user and you have any thoughts on this, please leave a comment. Is it too much of a burden to install from github?

I'm inclined to stay off NPM but am open to discussion.

**Comment by VackerSimon** [comment]
I think it's fine as it is right now

**Comment by jrudess** [comment]
I don't have any strong preference to publish via npm, since npm supports fetching directly from github anyway.  But it's also not really an issue if you do change to lowercase for npm publication, and will just update my end to match.

**Comment by ZombieAlex** [comment]
Thanks for the feedback. Will stay as-is for now.
