### ISSUE TITLE
How to release memory properly?

### ISSUE THREAD

**Issue by sstativa** [ZombieAlex/MFCAuto#7]
The following code might look weird, especially knowing that MFCAuto client can detect all changes related to the list of models, however, I don't think there are anything "criminal" in it and it should work fine. 

It works, however, node, started with `--trace_gc` parameter, shows that js heap grows slowly over the time. Therefore I assume either I release the `client` wrong or there is a memory leak in the code of MFCAuto.

What is your thoughts?

```js
'use strict';

var Promise = require('bluebird');
var mfc = require('MFCAuto');
var onlineModels = [];

function getModels() {
  var client = new mfc.Client();

  return Promise
    .try(() => client.connectAndWaitForModels())
    .then(() => {
      onlineModels = [];

      mfc.Model.knownModels.forEach((m) => {
        if (m.bestSession.vs !== mfc.STATE.Offline) {
          onlineModels.push(m.bestSession);
        }
      });

      client.disconnect();

      console.log(`${onlineModels.length} model(s) online`);
    });
}

function mainLoop() {
  Promise.try(() => getModels());

  setTimeout(mainLoop, 30 * 1000);
}

mainLoop();

```

This is a comparison of two snapshots, hopes it will give you some ideas.
<img width="1027" alt="screen shot 2017-02-04 at 22 20 06" src="https://cloud.githubusercontent.com/assets/3362679/22618104/d0fb9b96-eb28-11e6-827e-53925c224cc0.png">

**Comment by ZombieAlex** [comment]
MFC sends model information to the client only when a model is online.  And once MFCAuto knows about a model (including things like her name, her country, and other profile details) it never forgets about her.  So it's expected for memory use to grow over time as different, previously unknown, models come online and the model cache grows.

That cache is all in `mfc.Model.knownModels`.  It's a normal Map object.  If you want, you could clear it via `mfc.Model.knownModels.clear()`.  I haven't tested if clearing that knownModels introduces any other bugs, but I believe it should be ok.

That said, you shouldn't see extreme memory growth or unbounded leaks.  As an example, right now I happen to have a local MFCAuto client that's been running and connected non-stop for 8 days and it's using 256mb of memory.  Depending on your scenario that could still be too high for you, in which case I'd try the .clear().

Let me know if that doesn't help.  Thanks.
